openapi: 3.0.0
info:
  title: Simple User API
  description: A simple API to manage users.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /users:
    get:
      summary: Get a list of users
      description: Retrieve a list of users from the system.
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

