openapi: 3.0.0
info:
  title: Sample API
  description: API for demonstrating OpenAPI Generator
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
paths:
  /greet:
    get:
      summary: Greet the user
      operationId: greetUser
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: string
